### ISSUE TITLE
Backport to 3.4/5

### ISSUE THREAD

**Issue by 20milliliter** [20milliliter/godot-menubar#1]
As of right now, I can't say whether or not I will. If fixing the current issues takes less time than I anticipate, and its clear that there will be a substantial amount of time before 4.0 is released, I'll feel more open to it.

**Comment by 20milliliter** [comment]
Actually I think I will. It'll be a little bit but when I can find the time I'll try to.

**Comment by Askully** [comment]
I'm interested as I'm still on 3.4.1

**Comment by 20milliliter** [comment]
Obsolesced, as Godot 4 now has an official MenuBar node.
